name: Tailscale Test 2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Авторизация в Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_KEY }}
        tags: ${{ secrets.TAGS }}

    - name: Удержание раннера
      run: |
        set -euo pipefail
        echo "Exit node is active. Keeping runner alive for 235 minutes."
        sleep 14100

    - name: Очистка
      if: always()
      run: |
        sudo tailscale down || true
        sudo tailscale logout || true
